# Generated by Django 3.2.6 on 2021-10-13 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0003_auto_20211006_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
