# Generated by Django 3.2.6 on 2021-10-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0004_remove_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
