# Generated by Django 3.2.6 on 2021-10-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0009_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
