# Generated by Django 3.2.6 on 2021-10-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0011_auto_20211016_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
