# Generated by Django 3.2.6 on 2021-10-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0012_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
