# Generated by Django 3.2.6 on 2021-10-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0014_product_selled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selled',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
