# Generated by Django 3.2.6 on 2021-10-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0015_alter_product_selled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selled',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
