# Generated by Django 3.2.6 on 2021-10-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0016_auto_20211016_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping',
            new_name='shiping',
        ),
        migrations.AddField(
            model_name='order',
            name='paying',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
