# Generated by Django 3.2.6 on 2021-10-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0018_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='item',
        ),
    ]
